In [1]:
import pandas as pd  # Import pandas library as pd for data manipulation and analysis
import numpy as np   # Import numpy library as np for numerical operations
import os            # Import os library for interacting with the operating system (file operations)

In [2]:
path = r"C:\Users\toloz\Achivement 6 data immersion\02 data\air bnb"

In [5]:
df_listings = pd.read_csv(os.path.join(path, 'listings.csv'), index_col=False)  
# Read the 'listings.csv' file from the specified path using pandas' read_csv function
# os.path.join combines the file path and the filename to ensure the correct file path format across different OS
# index_col=False ensures that pandas does not treat any column as the index (default behavior)

In [7]:
df_listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2818,Quiet Garden View Room & Super Fast WiFi,3159,Daniel,NaN,Oostelijk Havengebied - Indische Buurt,52.365755,4.941419,Private room,59,3,248,2018-11-28,2.10,1,44
1,3209,"Quiet apt near center, great view",3806,Maartje,NaN,Westerpark,52.390225,4.873924,Entire home/apt,160,4,42,2018-08-29,1.03,1,47
2,20168,100%Centre-Studio 1 Private Floor/Bathroom,59484,Alex,NaN,Centrum-Oost,52.365087,4.893541,Entire home/apt,80,1,233,2018-11-30,2.18,2,198
3,25428,Lovely apt in City Centre (Jordaan),56142,Joan,NaN,Centrum-West,52.373114,4.883668,Entire home/apt,125,14,1,2018-01-21,0.09,2,141
4,27886,"Romantic, stylish B&B houseboat in canal district",97647,Flip,NaN,Centrum-West,52.386727,4.892078,Private room,150,2,171,2018-11-25,2.03,1,199

In [9]:
df_calendar = pd.read_csv(os.path.join(path,  'calendar.csv'), index_col = False)

In [10]:
df_calendar

         listing_id        date available    price
0              2818  2019-12-05         f      NaN
1             73208  2019-08-30         f      NaN
2             73208  2019-08-29         f      NaN
3             73208  2019-08-28         f      NaN
4             73208  2019-08-27         f      NaN
...             ...         ...       ...      ...
7310945    29979667  2018-12-11         t  $139.00
7310946    29979667  2018-12-10         t  $139.00
7310947    29979667  2018-12-09         t  $139.00
7310948    29979667  2018-12-08         t  $139.00
7310949    29979667  2018-12-07         t  $139.00

[7310950 rows x 4 columns]

In [11]:
print(df_calendar.dtypes)

listing_id     int64
date          object
available     object
price         object
dtype: object

In [12]:


# Specify the column dtype for the problematic column (column 87 in your case)
df_listings_details = pd.read_csv(
    os.path.join(path, 'listings_details.csv'), 
    index_col=False, 
    dtype={87: str}  # Assuming column 87 has mixed types and converting it to string
)

In [16]:
df_listings_details.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,2818,https://www.airbnb.com/rooms/2818,20181206172549,2018-12-06,Quiet Garden View Room & Super Fast WiFi,Quiet Garden View Room & Super Fast WiFi,I'm renting a bedroom (room overlooking the ga...,Quiet Garden View Room & Super Fast WiFi I'm r...,none,"Indische Buurt (""Indies Neighborhood"") is a ne...",...,f,NaN,{Amsterdam},t,f,strict_14_with_grace_period,f,f,1,2.10
1,3209,https://www.airbnb.com/rooms/3209,20181206172549,2018-12-06,"Quiet apt near center, great view",You will love our spacious (90 m2) bright apar...,"Our apartment has lots of light, a balcony and...",You will love our spacious (90 m2) bright apar...,none,Welcome to the Spaarndammerbuurt! From the beg...,...,f,NaN,{Amsterdam},f,f,moderate,f,f,1,1.03
2,20168,https://www.airbnb.com/rooms/20168,20181206172549,2018-12-06,100%Centre-Studio 1 Private Floor/Bathroom,"Cozy studio on your own private floor, 100% in...",For those who like all facets of city life. In...,"Cozy studio on your own private floor, 100% in...",none,Located just in between famous central canals....,...,f,NaN,{Amsterdam},f,f,strict_14_with_grace_period,f,f,2,2.18
3,25428,https://www.airbnb.com/rooms/25428,20181206172549,2018-12-06,Lovely apt in City Centre (Jordaan),NaN,"This nicely furnished, newly renovated apt is...","This nicely furnished, newly renovated apt is...",none,NaN,...,f,NaN,{Amsterdam},f,f,strict_14_with_grace_period,f,f,2,0.09
4,27886,https://www.airbnb.com/rooms/27886,20181206172549,2018-12-06,"Romantic, stylish B&B houseboat in canal district",Stylish and romantic houseboat on fantastic hi...,For a romantic couple: A beautifully restored ...,Stylish and romantic houseboat on fantastic hi...,none,"Central, quiet, safe, clean and beautiful.",...,f,NaN,{Amsterdam},t,f,strict_14_with_grace_period,f,f,1,2.03

In [19]:
df_listings = pd.read_csv(os.path.join(path,  'listings.csv'), index_col = False)

In [21]:
df_listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2818,Quiet Garden View Room & Super Fast WiFi,3159,Daniel,NaN,Oostelijk Havengebied - Indische Buurt,52.365755,4.941419,Private room,59,3,248,2018-11-28,2.10,1,44
1,3209,"Quiet apt near center, great view",3806,Maartje,NaN,Westerpark,52.390225,4.873924,Entire home/apt,160,4,42,2018-08-29,1.03,1,47
2,20168,100%Centre-Studio 1 Private Floor/Bathroom,59484,Alex,NaN,Centrum-Oost,52.365087,4.893541,Entire home/apt,80,1,233,2018-11-30,2.18,2,198
3,25428,Lovely apt in City Centre (Jordaan),56142,Joan,NaN,Centrum-West,52.373114,4.883668,Entire home/apt,125,14,1,2018-01-21,0.09,2,141
4,27886,"Romantic, stylish B&B houseboat in canal district",97647,Flip,NaN,Centrum-West,52.386727,4.892078,Private room,150,2,171,2018-11-25,2.03,1,199

In [23]:
df_neighbourhoods = pd.read_csv(os.path.join(path,  'neighbourhoods.csv'), index_col = False)

In [25]:
df_neighbourhoods.head()

   neighbourhood_group           neighbourhood
0                  NaN         Bijlmer-Centrum
1                  NaN            Bijlmer-Oost
2                  NaN           Bos en Lommer
3                  NaN  Buitenveldert - Zuidas
4                  NaN            Centrum-Oost

In [27]:
df_listings.rename(columns={'id': 'listing_id'}, inplace=True)

In [29]:
df_listings.head()

,listing_id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2818,Quiet Garden View Room & Super Fast WiFi,3159,Daniel,NaN,Oostelijk Havengebied - Indische Buurt,52.365755,4.941419,Private room,59,3,248,2018-11-28,2.10,1,44
1,3209,"Quiet apt near center, great view",3806,Maartje,NaN,Westerpark,52.390225,4.873924,Entire home/apt,160,4,42,2018-08-29,1.03,1,47
2,20168,100%Centre-Studio 1 Private Floor/Bathroom,59484,Alex,NaN,Centrum-Oost,52.365087,4.893541,Entire home/apt,80,1,233,2018-11-30,2.18,2,198
3,25428,Lovely apt in City Centre (Jordaan),56142,Joan,NaN,Centrum-West,52.373114,4.883668,Entire home/apt,125,14,1,2018-01-21,0.09,2,141
4,27886,"Romantic, stylish B&B houseboat in canal district",97647,Flip,NaN,Centrum-West,52.386727,4.892078,Private room,150,2,171,2018-11-25,2.03,1,199

In [31]:
df_listings.rename(columns={'price': 'price_per_night'}, inplace=True)

In [33]:
df_listings.head()

,listing_id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price_per_night,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2818,Quiet Garden View Room & Super Fast WiFi,3159,Daniel,NaN,Oostelijk Havengebied - Indische Buurt,52.365755,4.941419,Private room,59,3,248,2018-11-28,2.10,1,44
1,3209,"Quiet apt near center, great view",3806,Maartje,NaN,Westerpark,52.390225,4.873924,Entire home/apt,160,4,42,2018-08-29,1.03,1,47
2,20168,100%Centre-Studio 1 Private Floor/Bathroom,59484,Alex,NaN,Centrum-Oost,52.365087,4.893541,Entire home/apt,80,1,233,2018-11-30,2.18,2,198
3,25428,Lovely apt in City Centre (Jordaan),56142,Joan,NaN,Centrum-West,52.373114,4.883668,Entire home/apt,125,14,1,2018-01-21,0.09,2,141
4,27886,"Romantic, stylish B&B houseboat in canal district",97647,Flip,NaN,Centrum-West,52.386727,4.892078,Private room,150,2,171,2018-11-25,2.03,1,199

In [35]:
print(df_listings.dtypes)

listing_id                          int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group               float64
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price_per_night                     int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [37]:
df_listings.drop(columns=['neighbourhood_group'], inplace=True)

In [39]:
df_listings.head()

,listing_id,name,host_id,host_name,neighbourhood,latitude,longitude,room_type,price_per_night,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2818,Quiet Garden View Room & Super Fast WiFi,3159,Daniel,Oostelijk Havengebied - Indische Buurt,52.365755,4.941419,Private room,59,3,248,2018-11-28,2.10,1,44
1,3209,"Quiet apt near center, great view",3806,Maartje,Westerpark,52.390225,4.873924,Entire home/apt,160,4,42,2018-08-29,1.03,1,47
2,20168,100%Centre-Studio 1 Private Floor/Bathroom,59484,Alex,Centrum-Oost,52.365087,4.893541,Entire home/apt,80,1,233,2018-11-30,2.18,2,198
3,25428,Lovely apt in City Centre (Jordaan),56142,Joan,Centrum-West,52.373114,4.883668,Entire home/apt,125,14,1,2018-01-21,0.09,2,141
4,27886,"Romantic, stylish B&B houseboat in canal district",97647,Flip,Centrum-West,52.386727,4.892078,Private room,150,2,171,2018-11-25,2.03,1,199

In [41]:
df_listings.drop(columns=['host_name'], inplace=True)

In [43]:
df_neighbourhoods.head()

   neighbourhood_group           neighbourhood
0                  NaN         Bijlmer-Centrum
1                  NaN            Bijlmer-Oost
2                  NaN           Bos en Lommer
3                  NaN  Buitenveldert - Zuidas
4                  NaN            Centrum-Oost

In [44]:
print(df_neighbourhoods.dtypes)

neighbourhood_group    float64
neighbourhood           object
dtype: object

In [45]:
print(df_neighbourhoods.dtypes)

neighbourhood_group    float64
neighbourhood           object
dtype: object

In [46]:
df_neighbourhoods.drop(columns=['neighbourhood_group'], inplace=True)

In [47]:
df_neighbourhoods.head()

            neighbourhood
0         Bijlmer-Centrum
1            Bijlmer-Oost
2           Bos en Lommer
3  Buitenveldert - Zuidas
4            Centrum-Oost

In [48]:
df_listings_details = pd.read_csv(
    os.path.join(path, 'listings_details.csv'),
    dtype={'column_87_name': str},  # Replace 'column_87_name' with the actual name of the column
    index_col=False
)

C:\Users\toloz\AppData\Local\Temp\ipykernel_12380\2819797270.py:1: DtypeWarning: Columns (87) have mixed types. Specify dtype option on import or set low_memory=False.
  df_listings_details = pd.read_csv(

In [49]:
df123 = pd.read_csv(os.path.join(path, 'listings_details.csv'), usecols=[87])
print(df123.head())  # This will show the first few rows of column 87

  license
0     NaN
1     NaN
2     NaN
3     NaN
4     NaN

C:\Users\toloz\AppData\Local\Temp\ipykernel_12380\3323918996.py:1: DtypeWarning: Columns (87) have mixed types. Specify dtype option on import or set low_memory=False.
  df123 = pd.read_csv(os.path.join(path, 'listings_details.csv'), usecols=[87])

In [50]:
df_listings_details = pd.read_csv(
    os.path.join(path, 'listings_details.csv'),
    dtype={87: str},  # Column 87 as string
    index_col=False
)

In [51]:
df_listings_details.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,2818,https://www.airbnb.com/rooms/2818,20181206172549,2018-12-06,Quiet Garden View Room & Super Fast WiFi,Quiet Garden View Room & Super Fast WiFi,I'm renting a bedroom (room overlooking the ga...,Quiet Garden View Room & Super Fast WiFi I'm r...,none,"Indische Buurt (""Indies Neighborhood"") is a ne...",...,f,NaN,{Amsterdam},t,f,strict_14_with_grace_period,f,f,1,2.10
1,3209,https://www.airbnb.com/rooms/3209,20181206172549,2018-12-06,"Quiet apt near center, great view",You will love our spacious (90 m2) bright apar...,"Our apartment has lots of light, a balcony and...",You will love our spacious (90 m2) bright apar...,none,Welcome to the Spaarndammerbuurt! From the beg...,...,f,NaN,{Amsterdam},f,f,moderate,f,f,1,1.03
2,20168,https://www.airbnb.com/rooms/20168,20181206172549,2018-12-06,100%Centre-Studio 1 Private Floor/Bathroom,"Cozy studio on your own private floor, 100% in...",For those who like all facets of city life. In...,"Cozy studio on your own private floor, 100% in...",none,Located just in between famous central canals....,...,f,NaN,{Amsterdam},f,f,strict_14_with_grace_period,f,f,2,2.18
3,25428,https://www.airbnb.com/rooms/25428,20181206172549,2018-12-06,Lovely apt in City Centre (Jordaan),NaN,"This nicely furnished, newly renovated apt is...","This nicely furnished, newly renovated apt is...",none,NaN,...,f,NaN,{Amsterdam},f,f,strict_14_with_grace_period,f,f,2,0.09
4,27886,https://www.airbnb.com/rooms/27886,20181206172549,2018-12-06,"Romantic, stylish B&B houseboat in canal district",Stylish and romantic houseboat on fantastic hi...,For a romantic couple: A beautifully restored ...,Stylish and romantic houseboat on fantastic hi...,none,"Central, quiet, safe, clean and beautiful.",...,f,NaN,{Amsterdam},t,f,strict_14_with_grace_period,f,f,1,2.03

In [52]:
print(df_listings_details.dtypes)

id                                    int64
listing_url                          object
scrape_id                             int64
last_scraped                         object
name                                 object
                                     ...
cancellation_policy                  object
require_guest_profile_picture        object
require_guest_phone_verification     object
calculated_host_listings_count        int64
reviews_per_month                   float64
Length: 96, dtype: object

In [53]:
pd.set_option('display.max_columns', None)

In [54]:
print(df_listings_details.dtypes)

id                                    int64
listing_url                          object
scrape_id                             int64
last_scraped                         object
name                                 object
                                     ...
cancellation_policy                  object
require_guest_profile_picture        object
require_guest_phone_verification     object
calculated_host_listings_count        int64
reviews_per_month                   float64
Length: 96, dtype: object

In [55]:
print(df_listings_details.dtypes)

id                                    int64
listing_url                          object
scrape_id                             int64
last_scraped                         object
name                                 object
                                     ...
cancellation_policy                  object
require_guest_profile_picture        object
require_guest_phone_verification     object
calculated_host_listings_count        int64
reviews_per_month                   float64
Length: 96, dtype: object

In [56]:
dtype_df_listings_details = pd.DataFrame(df_listings_details.dtypes, columns=['Dtype'])
print(dtype_df_listings_details)

                                    Dtype
id                                  int64
listing_url                        object
scrape_id                           int64
last_scraped                       object
name                               object
...                                   ...
cancellation_policy                object
require_guest_profile_picture      object
require_guest_phone_verification   object
calculated_host_listings_count      int64
reviews_per_month                 float64

[96 rows x 1 columns]

In [57]:
print(df_listings_details.dtypes.to_string())

id                                    int64
listing_url                          object
scrape_id                             int64
last_scraped                         object
name                                 object
summary                              object
space                                object
description                          object
experiences_offered                  object
neighborhood_overview                object
notes                                object
transit                              object
access                               object
interaction                          object
house_rules                          object
thumbnail_url                       float64
medium_url                          float64
picture_url                          object
xl_picture_url                      float64
host_id                               int64
host_url                             object
host_name                            object
host_since                           object
host_location                        object
host_about                           object
host_response_time                   object
host_response_rate                   object
host_acceptance_rate                float64
host_is_superhost                    object
host_thumbnail_url                   object
host_picture_url                     object
host_neighbourhood                   object
host_listings_count                 float64
host_total_listings_count           float64
host_verifications                   object
host_has_profile_pic                 object
host_identity_verified               object
street                               object
neighbourhood                        object
neighbourhood_cleansed               object
neighbourhood_group_cleansed        float64
city                                 object
state                                object
zipcode                              object
market                               object
smart_location                       object
country_code                         object
country                              object
latitude                            float64
longitude                           float64
is_location_exact                    object
property_type                        object
room_type                            object
accommodates                          int64
bathrooms                           float64
bedrooms                            float64
beds                                float64
bed_type                             object
amenities                            object
square_feet                         float64
price                                object
weekly_price                         object
monthly_price                        object
security_deposit                     object
cleaning_fee                         object
guests_included                       int64
extra_people                         object
minimum_nights                        int64
maximum_nights                        int64
calendar_updated                     object
has_availability                     object
availability_30                       int64
availability_60                       int64
availability_90                       int64
availability_365                      int64
calendar_last_scraped                object
number_of_reviews                     int64
first_review                         object
last_review                          object
review_scores_rating                float64
review_scores_accuracy              float64
review_scores_cleanliness           float64
review_scores_checkin               float64
review_scores_communication         float64
review_scores_location              float64
review_scores_value                 float64
requires_license                     object
license                              object
jurisdiction_names                   object
instant_bookable                     object
is_business_travel_ready             object
cancellation_policy                  object
require_guest_profile_picture        object
require_guest_phone_verification     object
calculated_host_listings_count        int64
reviews_per_month                   float64

In [58]:
columns_to_drop = [
    'host_id', 'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
    'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
    'scrape_id', 'last_scraped', 'notes', 'transit', 'interaction', 'thumbnail_url',
    'medium_url', 'xl_picture_url', 'host_picture_url', 'first_review', 'last_review',
    'jurisdiction_names', 'instant_bookable', 'is_business_travel_ready',
    'require_guest_profile_picture', 'require_guest_phone_verification', 'host_thumbnail_url',
    'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications',
    'host_has_profile_pic', 'host_identity_verified'
]

df_listings_details.drop(columns=columns_to_drop, inplace=True)

In [59]:
df_listings_details.head()

,id,listing_url,name,summary,space,description,experiences_offered,neighborhood_overview,access,house_rules,picture_url,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,cancellation_policy,calculated_host_listings_count,reviews_per_month
0,2818,https://www.airbnb.com/rooms/2818,Quiet Garden View Room & Super Fast WiFi,Quiet Garden View Room & Super Fast WiFi,I'm renting a bedroom (room overlooking the ga...,Quiet Garden View Room & Super Fast WiFi I'm r...,none,"Indische Buurt (""Indies Neighborhood"") is a ne...",NaN,Please: - Leave your shoes in the entrance - ...,https://a0.muscache.com/im/pictures/10272854/8...,"Amsterdam, North Holland, Netherlands",Indische Buurt,Oostelijk Havengebied - Indische Buurt,NaN,Amsterdam,North Holland,NaN,Amsterdam,"Amsterdam, Netherlands",NL,Netherlands,52.365755,4.941419,f,Apartment,Private room,2,1.5,1.0,2.0,Real Bed,"{Internet,Wifi,""Paid parking off premises"",""Bu...",NaN,$59.00,NaN,"$1,500.00",$100.00,$50.00,1,$20.00,3,15,today,t,17,44,44,44,2018-12-06,248,97.0,10.0,10.0,10.0,10.0,9.0,10.0,f,NaN,strict_14_with_grace_period,1,2.10
1,3209,https://www.airbnb.com/rooms/3209,"Quiet apt near center, great view",You will love our spacious (90 m2) bright apar...,"Our apartment has lots of light, a balcony and...",You will love our spacious (90 m2) bright apar...,none,Welcome to the Spaarndammerbuurt! From the beg...,You will have the entire house to yourself.,"Our house comes with our very sweet, but old (...",https://a0.muscache.com/im/pictures/88955424/4...,"Amsterdam, Noord-Holland, Netherlands",Spaarndammer en Zeeheldenbuurt,Westerpark,NaN,Amsterdam,Noord-Holland,1013 XE,Amsterdam,"Amsterdam, Netherlands",NL,Netherlands,52.390225,4.873924,t,Apartment,Entire home/apt,5,1.0,2.0,2.0,Real Bed,"{Internet,Wifi,Kitchen,""Paid parking off premi...",NaN,$160.00,$543.00,"$2,000.00",$300.00,$40.00,2,$15.00,4,20,7 weeks ago,t,0,0,0,47,2018-12-06,42,96.0,10.0,9.0,10.0,10.0,9.0,9.0,f,NaN,moderate,1,1.03
2,20168,https://www.airbnb.com/rooms/20168,100%Centre-Studio 1 Private Floor/Bathroom,"Cozy studio on your own private floor, 100% in...",For those who like all facets of city life. In...,"Cozy studio on your own private floor, 100% in...",none,Located just in between famous central canals....,NaN,This studio/room takes entire floor and has it...,https://a0.muscache.com/im/pictures/69979664/3...,"Amsterdam, North Holland, Netherlands",Grachtengordel,Centrum-Oost,NaN,Amsterdam,North Holland,1017,Amsterdam,"Amsterdam, Netherlands",NL,Netherlands,52.365087,4.893541,t,Townhouse,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,Internet,Wifi,""Paid parking off premises"",...",NaN,$80.00,NaN,NaN,NaN,NaN,2,$0.00,1,1000,today,t,0,7,24,198,2018-12-06,233,87.0,9.0,10.0,9.0,9.0,10.0,9.0,f,NaN,strict_14_with_grace_period,2,2.18
3,25428,https://www.airbnb.com/rooms/25428,Lovely apt in City Centre (Jordaan),NaN,"This nicely furnished, newly renovated apt is...","This nicely furnished, newly renovated apt is...",none,NaN,The apartment is about 75 meters or 800 square...,"The building is a quiet building, so please do...",https://a0.muscache.com/im/pictures/138431/707...,"Amsterdam, North Holland, Netherlands",Grachtengordel,Centrum-West,NaN,Amsterdam,North Holland,1016,Amsterdam,"Amsterdam, Netherlands",NL,Netherlands,52.373114,4.883668,f,Apartment,Entire home/apt,3,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,Kitchen,Elevator,...",NaN,$125.00,$650.00,"$2,000.00",$300.00,$40.00,2,$10.00,14,60,2 days ago,t,2,32,44,141,2018-12-06,1,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,strict_14_with_grace_period,2,0.09
4,27886,https://www.airbnb.com/rooms/27886,"Romantic, stylish B&B houseboat in canal district",Stylish and romantic houseboat on fantastic hi...,For a romantic couple: A beautifully restored ...,Stylish and romantic houseboat on fantastic hi...,none,"Central, quiet, safe, clean and beautiful.","Your own apartment, nothing shared","All the facilities are included ( cleaning , ...",https://a0.muscache.com/im/pictures/02c2da9d-6...,"Amsterdam, North Holland, Netherlands",Westelijke Eilanden,Centrum-West,NaN,Amsterdam,North Holland,1013,Amsterdam,"Amsterdam, Netherlands",NL,Netherlands,52.386727,4.892078,t,Houseboat,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,Internet,Wifi,Breakfast,Heating,""Smoke det...",NaN,$150.00,$810.00,"$2,500.00",$0.00,$0.00,1,$0.00,2,730,today,t,16,37,54,199,2018-12-06,171,99.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,strict_14_with_grace_period,1,2.03

In [60]:
# Get the shape of the DataFrame (rows, columns)
num_rows, num_columns = df_listings_details.shape

# Print the result
print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_columns}")

Number of rows: 20030
Number of columns: 63

In [61]:
# List of columns to delete
columns_to_delete = [
    'summary', 
    'listing_url', 
    'description', 
    'house_rules', 
    'picture_url', 
    'market', 
    'calendar_last_scraped', 
    'reviews_per_month'
]

# Drop the columns from the DataFrame
df_listings_details.drop(columns=columns_to_delete, inplace=True)

# Check the new shape of the DataFrame
print(f"Updated DataFrame shape: {df_listings_details.shape}")

Updated DataFrame shape: (20030, 55)

In [62]:
print(df_listings_details.dtypes)

id                                  int64
name                               object
space                              object
experiences_offered                object
neighborhood_overview              object
access                             object
street                             object
neighbourhood                      object
neighbourhood_cleansed             object
neighbourhood_group_cleansed      float64
city                               object
state                              object
zipcode                            object
smart_location                     object
country_code                       object
country                            object
latitude                          float64
longitude                         float64
is_location_exact                  object
property_type                      object
room_type                          object
accommodates                        int64
bathrooms                         float64
bedrooms                          float64
beds                              float64
bed_type                           object
amenities                          object
square_feet                       float64
price                              object
weekly_price                       object
monthly_price                      object
security_deposit                   object
cleaning_fee                       object
guests_included                     int64
extra_people                       object
minimum_nights                      int64
maximum_nights                      int64
calendar_updated                   object
has_availability                   object
availability_30                     int64
availability_60                     int64
availability_90                     int64
availability_365                    int64
number_of_reviews                   int64
review_scores_rating              float64
review_scores_accuracy            float64
review_scores_cleanliness         float64
review_scores_checkin             float64
review_scores_communication       float64
review_scores_location            float64
review_scores_value               float64
requires_license                   object
license                            object
cancellation_policy                object
calculated_host_listings_count      int64
dtype: object

In [63]:
df_listings_details.head()

,id,name,space,experiences_offered,neighborhood_overview,access,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,cancellation_policy,calculated_host_listings_count
0,2818,Quiet Garden View Room & Super Fast WiFi,I'm renting a bedroom (room overlooking the ga...,none,"Indische Buurt (""Indies Neighborhood"") is a ne...",NaN,"Amsterdam, North Holland, Netherlands",Indische Buurt,Oostelijk Havengebied - Indische Buurt,NaN,Amsterdam,North Holland,NaN,"Amsterdam, Netherlands",NL,Netherlands,52.365755,4.941419,f,Apartment,Private room,2,1.5,1.0,2.0,Real Bed,"{Internet,Wifi,""Paid parking off premises"",""Bu...",NaN,$59.00,NaN,"$1,500.00",$100.00,$50.00,1,$20.00,3,15,today,t,17,44,44,44,248,97.0,10.0,10.0,10.0,10.0,9.0,10.0,f,NaN,strict_14_with_grace_period,1
1,3209,"Quiet apt near center, great view","Our apartment has lots of light, a balcony and...",none,Welcome to the Spaarndammerbuurt! From the beg...,You will have the entire house to yourself.,"Amsterdam, Noord-Holland, Netherlands",Spaarndammer en Zeeheldenbuurt,Westerpark,NaN,Amsterdam,Noord-Holland,1013 XE,"Amsterdam, Netherlands",NL,Netherlands,52.390225,4.873924,t,Apartment,Entire home/apt,5,1.0,2.0,2.0,Real Bed,"{Internet,Wifi,Kitchen,""Paid parking off premi...",NaN,$160.00,$543.00,"$2,000.00",$300.00,$40.00,2,$15.00,4,20,7 weeks ago,t,0,0,0,47,42,96.0,10.0,9.0,10.0,10.0,9.0,9.0,f,NaN,moderate,1
2,20168,100%Centre-Studio 1 Private Floor/Bathroom,For those who like all facets of city life. In...,none,Located just in between famous central canals....,NaN,"Amsterdam, North Holland, Netherlands",Grachtengordel,Centrum-Oost,NaN,Amsterdam,North Holland,1017,"Amsterdam, Netherlands",NL,Netherlands,52.365087,4.893541,t,Townhouse,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,Internet,Wifi,""Paid parking off premises"",...",NaN,$80.00,NaN,NaN,NaN,NaN,2,$0.00,1,1000,today,t,0,7,24,198,233,87.0,9.0,10.0,9.0,9.0,10.0,9.0,f,NaN,strict_14_with_grace_period,2
3,25428,Lovely apt in City Centre (Jordaan),"This nicely furnished, newly renovated apt is...",none,NaN,The apartment is about 75 meters or 800 square...,"Amsterdam, North Holland, Netherlands",Grachtengordel,Centrum-West,NaN,Amsterdam,North Holland,1016,"Amsterdam, Netherlands",NL,Netherlands,52.373114,4.883668,f,Apartment,Entire home/apt,3,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,Kitchen,Elevator,...",NaN,$125.00,$650.00,"$2,000.00",$300.00,$40.00,2,$10.00,14,60,2 days ago,t,2,32,44,141,1,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,strict_14_with_grace_period,2
4,27886,"Romantic, stylish B&B houseboat in canal district",For a romantic couple: A beautifully restored ...,none,"Central, quiet, safe, clean and beautiful.","Your own apartment, nothing shared","Amsterdam, North Holland, Netherlands",Westelijke Eilanden,Centrum-West,NaN,Amsterdam,North Holland,1013,"Amsterdam, Netherlands",NL,Netherlands,52.386727,4.892078,t,Houseboat,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,Internet,Wifi,Breakfast,Heating,""Smoke det...",NaN,$150.00,$810.00,"$2,500.00",$0.00,$0.00,1,$0.00,2,730,today,t,16,37,54,199,171,99.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,strict_14_with_grace_period,1

In [64]:
df_listings

,listing_id,name,host_id,neighbourhood,latitude,longitude,room_type,price_per_night,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2818,Quiet Garden View Room & Super Fast WiFi,3159,Oostelijk Havengebied - Indische Buurt,52.365755,4.941419,Private room,59,3,248,2018-11-28,2.10,1,44
1,3209,"Quiet apt near center, great view",3806,Westerpark,52.390225,4.873924,Entire home/apt,160,4,42,2018-08-29,1.03,1,47
2,20168,100%Centre-Studio 1 Private Floor/Bathroom,59484,Centrum-Oost,52.365087,4.893541,Entire home/apt,80,1,233,2018-11-30,2.18,2,198
3,25428,Lovely apt in City Centre (Jordaan),56142,Centrum-West,52.373114,4.883668,Entire home/apt,125,14,1,2018-01-21,0.09,2,141
4,27886,"Romantic, stylish B&B houseboat in canal district",97647,Centrum-West,52.386727,4.892078,Private room,150,2,171,2018-11-25,2.03,1,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20025,30576148,Family House City + free Parking+garden (160 m2),13399651,Watergraafsmeer,52.345999,4.952145,Entire home/apt,340,7,0,NaN,NaN,1,11
20026,30577727,Home Sweet Home in Indische Buurt,1595885,Oostelijk Havengebied - Indische Buurt,52.362412,4.932467,Entire home/apt,150,3,0,NaN,NaN,2,16
20027,30578037,Amsterdam Cozy apartment nearby center,87866499,Oud-Oost,52.362431,4.926912,Entire home/apt,80,10,0,NaN,NaN,2,210
20028,30579673,Home Sweet Home for a Guest or a Couple,1595885,Oostelijk Havengebied - Indische Buurt,52.363780,4.932493,Private room,55,2,0,NaN,NaN,2,31
20029,30580413,Cosy two bedroom appartment near 'de Pijp'!,27212057,De Pijp - Rivierenbuurt,52.346911,4.901932,Entire home/apt,220,5,0,NaN,NaN,1,14

In [65]:
df_calendar.head()

   listing_id        date available price
0        2818  2019-12-05         f   NaN
1       73208  2019-08-30         f   NaN
2       73208  2019-08-29         f   NaN
3       73208  2019-08-28         f   NaN
4       73208  2019-08-27         f   NaN

In [66]:
df_listings_details

,id,name,space,experiences_offered,neighborhood_overview,access,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,cancellation_policy,calculated_host_listings_count
0,2818,Quiet Garden View Room & Super Fast WiFi,I'm renting a bedroom (room overlooking the ga...,none,"Indische Buurt (""Indies Neighborhood"") is a ne...",NaN,"Amsterdam, North Holland, Netherlands",Indische Buurt,Oostelijk Havengebied - Indische Buurt,NaN,Amsterdam,North Holland,NaN,"Amsterdam, Netherlands",NL,Netherlands,52.365755,4.941419,f,Apartment,Private room,2,1.5,1.0,2.0,Real Bed,"{Internet,Wifi,""Paid parking off premises"",""Bu...",NaN,$59.00,NaN,"$1,500.00",$100.00,$50.00,1,$20.00,3,15,today,t,17,44,44,44,248,97.0,10.0,10.0,10.0,10.0,9.0,10.0,f,NaN,strict_14_with_grace_period,1
1,3209,"Quiet apt near center, great view","Our apartment has lots of light, a balcony and...",none,Welcome to the Spaarndammerbuurt! From the beg...,You will have the entire house to yourself.,"Amsterdam, Noord-Holland, Netherlands",Spaarndammer en Zeeheldenbuurt,Westerpark,NaN,Amsterdam,Noord-Holland,1013 XE,"Amsterdam, Netherlands",NL,Netherlands,52.390225,4.873924,t,Apartment,Entire home/apt,5,1.0,2.0,2.0,Real Bed,"{Internet,Wifi,Kitchen,""Paid parking off premi...",NaN,$160.00,$543.00,"$2,000.00",$300.00,$40.00,2,$15.00,4,20,7 weeks ago,t,0,0,0,47,42,96.0,10.0,9.0,10.0,10.0,9.0,9.0,f,NaN,moderate,1
2,20168,100%Centre-Studio 1 Private Floor/Bathroom,For those who like all facets of city life. In...,none,Located just in between famous central canals....,NaN,"Amsterdam, North Holland, Netherlands",Grachtengordel,Centrum-Oost,NaN,Amsterdam,North Holland,1017,"Amsterdam, Netherlands",NL,Netherlands,52.365087,4.893541,t,Townhouse,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,Internet,Wifi,""Paid parking off premises"",...",NaN,$80.00,NaN,NaN,NaN,NaN,2,$0.00,1,1000,today,t,0,7,24,198,233,87.0,9.0,10.0,9.0,9.0,10.0,9.0,f,NaN,strict_14_with_grace_period,2
3,25428,Lovely apt in City Centre (Jordaan),"This nicely furnished, newly renovated apt is...",none,NaN,The apartment is about 75 meters or 800 square...,"Amsterdam, North Holland, Netherlands",Grachtengordel,Centrum-West,NaN,Amsterdam,North Holland,1016,"Amsterdam, Netherlands",NL,Netherlands,52.373114,4.883668,f,Apartment,Entire home/apt,3,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,Kitchen,Elevator,...",NaN,$125.00,$650.00,"$2,000.00",$300.00,$40.00,2,$10.00,14,60,2 days ago,t,2,32,44,141,1,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,strict_14_with_grace_period,2
4,27886,"Romantic, stylish B&B houseboat in canal district",For a romantic couple: A beautifully restored ...,none,"Central, quiet, safe, clean and beautiful.","Your own apartment, nothing shared","Amsterdam, North Holland, Netherlands",Westelijke Eilanden,Centrum-West,NaN,Amsterdam,North Holland,1013,"Amsterdam, Netherlands",NL,Netherlands,52.386727,4.892078,t,Houseboat,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,Internet,Wifi,Breakfast,Heating,""Smoke det...",NaN,$150.00,$810.00,"$2,500.00",$0.00,$0.00,1,$0.00,2,730,today,t,16,37,54,199,171,99.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,strict_14_with_grace_period,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20025,30576148,Family House City + free Parking+garden (160 m2),"Our house is a spacious family house, just ren...",none,"Restaurants supermarkets, 5 Minutes inner inn...",You have access to our house all privately. Wi...,"Amsterdam, Noord-Holland, Netherlands",Watergraafsmeer,Watergraafsmeer,NaN,Amsterdam,Noord-Holland,1098 VV,"Amsterdam, Netherlands",NL,Netherlands,52.345999,4.952145,t,House,Entire home/apt,4,2.0,3.0,4.0,Real Bed,"{TV,Wifi,Kitchen,""Free parking on premises"",He...",NaN,$340.00,NaN,NaN,$500.00,$60.00,1,$0.00,7,12,today,t,11,11,11,11,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,strict_14_with_grace_period,1
20026,30577727,Home Sweet Home in Indische Buurt,We have fluffy bedsheets and cozy lighning. Th...,none,My Home Sweet Home is located in the beautiful...,NaN,"Amsterdam, Noord-Holland, Netherlands",Indische Buurt,Oostelijk Havengebied - Indische Buurt,NaN,Amsterdam,Noord-Holland,1094,"Amsterdam, Netherlands",NL,Netherlands,52.362412,4.932467,t,Apartment,Entire home/apt,3,1.0,2.0,3.0,Real Bed,"{TV,Wifi,Kitchen,Essentials,""Hair dryer"",Iron}",NaN,$150.00,NaN,NaN,$0.00,$25.00,1,$0.00,3,14,today,t,14,16,16,16,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,flexible,2
20027,30578037,Amsterdam Cozy apartment nearby center,NaN,none,NaN,NaN,"Amsterdam, NH, Netherlands",Indische Buurt,Oud-Oost,NaN,Amsterdam,NH,1093 GB,"Amsterdam, Netherlands",NL,Netherlands,52.362431,4.926912,f,Apartment,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Wifi,Kitchen,""Smoking allowed"",...",NaN,$80.00,NaN,NaN,NaN,NaN,1,$0.00,10,22,today,t,0,3,22,210,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,moderate,2
20028,30579673,Home Sweet Home for a Guest or a Couple,There are fluffy bedsheets and cozy lightning....,none,My Home Sweet Home is located in the beautiful...,The small and cosy bedroom will be your room t...,"Amsterdam, Noord-Holland, Netherlands",Indische Buurt,Oostelijk Havengebied - Indische Buurt,NaN,Amsterdam,Noord-Holland,1094,"Amsterdam, Netherlands",NL,Netherlands,52.363780,4.932493,t,Apartment,Private room,2,1.0,1.0,1.0,Real Bed,"{TV,Wifi,Kitchen,Essentials,""Hair dryer"",Iron}",NaN,$55.00,NaN,NaN,NaN,NaN,1,$0.00,2,15,today,t,7,31,31,31,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,flexible,2
20029,30580413,Cosy two bedroom appartment near 'de Pijp'!,NaN,none,NaN,Guests will have full access to the apartment.,"Amsterdam, Noord-Holland, Netherlands",Rivierenbuurt,De Pijp - Rivierenbuurt,NaN,Amsterdam,Noord-Holland,1078 CL,"Amsterdam, Netherlands",NL,Netherlands,52.346911,4.901932,t,Apartment,Entire home/apt,4,1.0,2.0,2.0,Real Bed,"{TV,Wifi,Kitchen,""Pets allowed"",Heating,Washer...",NaN,$220.00,NaN,NaN,$0.00,$30.00,1,$0.00,5,1125,today,t,14,14,14,14,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,flexible,1

In [67]:
 df_neighbourhoods.head()

            neighbourhood
0         Bijlmer-Centrum
1            Bijlmer-Oost
2           Bos en Lommer
3  Buitenveldert - Zuidas
4            Centrum-Oost

## Consistency Checks

## Checking for missing values

In [70]:
# Check for missing values
df_listings.isnull().sum()

listing_id                           0
name                                38
host_id                              0
neighbourhood                        0
latitude                             0
longitude                            0
room_type                            0
price_per_night                      0
minimum_nights                       0
number_of_reviews                    0
last_review                       2406
reviews_per_month                 2406
calculated_host_listings_count       0
availability_365                     0
dtype: int64

In [71]:
df_calendar.isnull().sum()

listing_id          0
date                0
available           0
price         6110879
dtype: int64

In [72]:
df_listings_details.isnull().sum()

id                                    0
name                                 38
space                              5451
experiences_offered                   0
neighborhood_overview              6773
access                             7803
street                                0
neighbourhood                      1653
neighbourhood_cleansed                0
neighbourhood_group_cleansed      20030
city                                  4
state                               127
zipcode                             866
smart_location                        0
country_code                          0
country                               0
latitude                              0
longitude                             0
is_location_exact                     0
property_type                         0
room_type                             0
accommodates                          0
bathrooms                            10
bedrooms                              8
beds                                  7
bed_type                              0
amenities                             0
square_feet                       19624
price                                 0
weekly_price                      17187
monthly_price                     18469
security_deposit                   6166
cleaning_fee                       3629
guests_included                       0
extra_people                          0
minimum_nights                        0
maximum_nights                        0
calendar_updated                      0
has_availability                      0
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
number_of_reviews                     0
review_scores_rating               2639
review_scores_accuracy             2649
review_scores_cleanliness          2647
review_scores_checkin              2661
review_scores_communication        2652
review_scores_location             2660
review_scores_value                2659
requires_license                      0
license                           20021
cancellation_policy                   0
calculated_host_listings_count        0
dtype: int64

In [73]:
 df_neighbourhoods.isnull().sum()

neighbourhood    0
dtype: int64

In [74]:
# delete Price value from calendar since its missing 83% of the values 
df_calendar.drop(columns=['price'], inplace=True)

# Verify that the column is removed
print(df_calendar.columns)

Index(['listing_id', 'date', 'available'], dtype='object')

In [75]:
# Fill missing 'last_review' with a placeholder
df_listings['last_review'].fillna('Never Reviewed', inplace=True)

# Fill missing 'reviews_per_month' with 0 (indicating no reviews)
df_listings['reviews_per_month'].fillna(0, inplace=True)

# For 'name', you can fill with "Unknown" if you need to keep the rows
df_listings['name'].fillna('Unknown', inplace=True)

# Check if the missing values were filled
print(df_listings.isnull().sum())

listing_id                        0
name                              0
host_id                           0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price_per_night                   0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [76]:



# 1. Leave `neighbourhood` as-is (no imputation)
# No action needed for 'neighbourhood' as we leave the missing values.

# 2. Drop the `neighbourhood_group_cleansed` column if it exists
if 'neighbourhood_group_cleansed' in df_listings_details.columns:
    df_listings_details.drop('neighbourhood_group_cleansed', axis=1, inplace=True)

# 3. Leave `city` as-is (no imputation)
# No action needed for 'city' as we leave the missing values.

# 4. Leave `zipcode` and `state` columns as they are with missing values (no action needed)

# 5. Convert relevant columns to numeric (removing currency symbols and commas)
def convert_to_numeric(col):
    # Remove any non-numeric characters like '$' and ',' and convert to numeric
    return pd.to_numeric(col.replace({'\$': '', ',': ''}, regex=True), errors='coerce')

# List of columns that are supposed to be numeric but may contain non-numeric values
numeric_columns = ['price', 'weekly_price', 'monthly_price', 'security_deposit', 
                   'cleaning_fee', 'bathrooms', 'bedrooms', 'beds']

# Apply the conversion function to those columns
for col in numeric_columns:
    df_listings_details[col] = convert_to_numeric(df_listings_details[col])

# 6. Impute other missing values in columns (e.g., 'space', 'access', etc.)
# For text columns like 'space', 'access', 'neighborhood_overview' etc., fill with placeholder text
df_listings_details['space'].fillna('No space description available', inplace=True)
df_listings_details['access'].fillna('No access description available', inplace=True)
df_listings_details['neighborhood_overview'].fillna('No overview available', inplace=True)

# 7. For numerical columns, impute missing values with the median (e.g., `bathrooms`, `bedrooms`, `security_deposit`, etc.)
numerical_cols = ['bathrooms', 'bedrooms', 'beds', 'security_deposit', 'cleaning_fee', 'weekly_price', 'monthly_price']
for col in numerical_cols:
    df_listings_details[col].fillna(df_listings_details[col].median(), inplace=True)

# 8. For columns like `price`, which should have no missing values, ensure they are correctly filled (e.g., impute with median if needed)
df_listings_details['price'].fillna(df_listings_details['price'].median(), inplace=True)

# 9. For review score columns (e.g., `review_scores_rating`, `review_scores_accuracy`, etc.), we can impute with the mean or median.
review_cols = [
    'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness',
    'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value'
]
for col in review_cols:
    df_listings_details[col].fillna(df_listings_details[col].median(), inplace=True)

# If you're done with all the missing values, you can check the result
print(df_listings_details.isnull().sum())  # Check if there are any missing values left

# Save the cleaned data if needed
# df_listings_details.to_csv('cleaned_listing_details.csv', index=False)

id                                    0
name                                 38
space                                 0
experiences_offered                   0
neighborhood_overview                 0
access                                0
street                                0
neighbourhood                      1653
neighbourhood_cleansed                0
city                                  4
state                               127
zipcode                             866
smart_location                        0
country_code                          0
country                               0
latitude                              0
longitude                             0
is_location_exact                     0
property_type                         0
room_type                             0
accommodates                          0
bathrooms                             0
bedrooms                              0
beds                                  0
bed_type                              0
amenities                             0
square_feet                       19624
price                                 0
weekly_price                          0
monthly_price                         0
security_deposit                      0
cleaning_fee                          0
guests_included                       0
extra_people                          0
minimum_nights                        0
maximum_nights                        0
calendar_updated                      0
has_availability                      0
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
number_of_reviews                     0
review_scores_rating                  0
review_scores_accuracy                0
review_scores_cleanliness             0
review_scores_checkin                 0
review_scores_communication           0
review_scores_location                0
review_scores_value                   0
requires_license                      0
license                           20021
cancellation_policy                   0
calculated_host_listings_count        0
dtype: int64

## Checking for different mixed type data

In [78]:
# for df_listings
for col in df_listings.columns.tolist():
    weird = (df_listings[col].apply(type) != type(df_listings[col].iloc[0])).any()
    if weird:
        print(col)
    else: 
        print('There is no mixed-type data')

listing_id
There is no mixed-type data
host_id
There is no mixed-type data
latitude
longitude
There is no mixed-type data
price_per_night
minimum_nights
number_of_reviews
There is no mixed-type data
reviews_per_month
calculated_host_listings_count
availability_365

In [79]:
# List of columns that were flagged as potentially having mixed types
columns_to_check = ['longitude', 'price_per_night', 'reviews_per_month', 
                    'calculated_host_listings_count', 'availability_365']

for col in columns_to_check:
    # Display the types of the first few entries in each column
    print(f"Checking column: {col}")
    print(df_listings[col].apply(type).head(10))  # Show the first 10 types
    print("---" * 20)

Checking column: longitude
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: longitude, dtype: object
------------------------------------------------------------
Checking column: price_per_night
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: price_per_night, dtype: object
------------------------------------------------------------
Checking column: reviews_per_month
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: reviews_per_month, dtype: object
------------------------------------------------------------
Checking column: calculated_host_listings_count
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: calculated_host_listings_count, dtype: object
------------------------------------------------------------
Checking column: availability_365
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: availability_365, dtype: object
------------------------------------------------------------

In [80]:
# Force the conversion of these columns to the correct types
df_listings['longitude'] = df_listings['longitude'].astype(float)
df_listings['price_per_night'] = df_listings['price_per_night'].astype(float)
df_listings['reviews_per_month'] = df_listings['reviews_per_month'].astype(float)
df_listings['calculated_host_listings_count'] = df_listings['calculated_host_listings_count'].astype(int)
df_listings['availability_365'] = df_listings['availability_365'].astype(int)

In [81]:
for col in df_listings.columns.tolist():
    print(f"Checking column: {col}")
    types = df_listings[col].apply(type)
    print(types.head(10))  # Print the types for the first 10 entries
    print("-" * 50)

Checking column: listing_id
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: listing_id, dtype: object
--------------------------------------------------
Checking column: name
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: name, dtype: object
--------------------------------------------------
Checking column: host_id
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: host_id, dtype: object
--------------------------------------------------
Checking column: neighbourhood
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: neighbourhood, dtype: object
--------------------------------------------------
Checking column: latitude
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: latitude, dtype: object
--------------------------------------------------
Checking column: longitude
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: longitude, dtype: object
--------------------------------------------------
Checking column: room_type
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: room_type, dtype: object
--------------------------------------------------
Checking column: price_per_night
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: price_per_night, dtype: object
--------------------------------------------------
Checking column: minimum_nights
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: minimum_nights, dtype: object
--------------------------------------------------
Checking column: number_of_reviews
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: number_of_reviews, dtype: object
--------------------------------------------------
Checking column: last_review
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: last_review, dtype: object
--------------------------------------------------
Checking column: reviews_per_month
0    <class 'float'>
1    <class 'float'>
2    <class 'float'>
3    <class 'float'>
4    <class 'float'>
5    <class 'float'>
6    <class 'float'>
7    <class 'float'>
8    <class 'float'>
9    <class 'float'>
Name: reviews_per_month, dtype: object
--------------------------------------------------
Checking column: calculated_host_listings_count
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: calculated_host_listings_count, dtype: object
--------------------------------------------------
Checking column: availability_365
0    <class 'int'>
1    <class 'int'>
2    <class 'int'>
3    <class 'int'>
4    <class 'int'>
5    <class 'int'>
6    <class 'int'>
7    <class 'int'>
8    <class 'int'>
9    <class 'int'>
Name: availability_365, dtype: object
--------------------------------------------------

In [82]:
for col in df_listings.columns:
    types = df_listings[col].apply(type)
    print(f"Checking column: {col}")
    print(types.value_counts())  # This will show how many unique types are present in each column
    print("-" * 50)

Checking column: listing_id
listing_id
<class 'int'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: name
name
<class 'str'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: host_id
host_id
<class 'int'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: neighbourhood
neighbourhood
<class 'str'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: latitude
latitude
<class 'float'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: longitude
longitude
<class 'float'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: room_type
room_type
<class 'str'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: price_per_night
price_per_night
<class 'float'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: minimum_nights
minimum_nights
<class 'int'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: number_of_reviews
number_of_reviews
<class 'int'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: last_review
last_review
<class 'str'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: reviews_per_month
reviews_per_month
<class 'float'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: calculated_host_listings_count
calculated_host_listings_count
<class 'int'>    20030
Name: count, dtype: int64
--------------------------------------------------
Checking column: availability_365
availability_365
<class 'int'>    20030
Name: count, dtype: int64
--------------------------------------------------

In [83]:
# for df_calendar 
for col in df_calendar.columns.tolist():
    weird = (df_calendar[col].apply(type) != type(df_calendar[col].iloc[0])).any()
    if weird:
        print(col)
    else: 
        print('There is no mixed-type data')

listing_id
There is no mixed-type data
There is no mixed-type data

In [84]:
df_calendar['listing_id'] = pd.to_numeric(df_calendar['listing_id'], errors='coerce')

In [85]:
# Fill NaN values with a placeholder or drop them, as needed
df_calendar['listing_id'].fillna(0, inplace=True)  # or df_calendar.dropna(subset=['listing_id'], inplace=True)

In [86]:
# Re-run the mixed-type check after cleaning the column
for col in df_calendar.columns.tolist():
    weird = (df_calendar[col].apply(type) != type(df_calendar[col].iloc[0])).any()
    if weird:
        print(col)
    else: 
        print('There is no mixed-type data')

listing_id
There is no mixed-type data
There is no mixed-type data

In [87]:
# Check the types of the 'listing_id' column to see if anything is still mixed
print(df_calendar['listing_id'].apply(type).value_counts())

listing_id
<class 'int'>    7310950
Name: count, dtype: int64

In [88]:
# df_listings_details
# Check for mixed types using value_counts for each column
for col in df_listings_details.columns:
    types_in_column = df_listings_details[col].apply(type).value_counts()
    if len(types_in_column) > 1:
        print(f"Mixed types in column: {col}")
    else:
        print(f"No mixed types in column: {col}")

No mixed types in column: id
Mixed types in column: name
No mixed types in column: space
No mixed types in column: experiences_offered
No mixed types in column: neighborhood_overview
No mixed types in column: access
No mixed types in column: street
Mixed types in column: neighbourhood
No mixed types in column: neighbourhood_cleansed
Mixed types in column: city
Mixed types in column: state
Mixed types in column: zipcode
No mixed types in column: smart_location
No mixed types in column: country_code
No mixed types in column: country
No mixed types in column: latitude
No mixed types in column: longitude
No mixed types in column: is_location_exact
No mixed types in column: property_type
No mixed types in column: room_type
No mixed types in column: accommodates
No mixed types in column: bathrooms
No mixed types in column: bedrooms
No mixed types in column: beds
No mixed types in column: bed_type
No mixed types in column: amenities
No mixed types in column: square_feet
No mixed types in column: price
No mixed types in column: weekly_price
No mixed types in column: monthly_price
No mixed types in column: security_deposit
No mixed types in column: cleaning_fee
No mixed types in column: guests_included
No mixed types in column: extra_people
No mixed types in column: minimum_nights
No mixed types in column: maximum_nights
No mixed types in column: calendar_updated
No mixed types in column: has_availability
No mixed types in column: availability_30
No mixed types in column: availability_60
No mixed types in column: availability_90
No mixed types in column: availability_365
No mixed types in column: number_of_reviews
No mixed types in column: review_scores_rating
No mixed types in column: review_scores_accuracy
No mixed types in column: review_scores_cleanliness
No mixed types in column: review_scores_checkin
No mixed types in column: review_scores_communication
No mixed types in column: review_scores_location
No mixed types in column: review_scores_value
No mixed types in column: requires_license
Mixed types in column: license
No mixed types in column: cancellation_policy
No mixed types in column: calculated_host_listings_count

In [89]:
# Convert all object columns to string and handle NaN values
df_listings_details = df_listings_details.apply(lambda x: x.fillna('Unknown') if x.dtype == 'O' else x)

# Check the result after converting
for col in df_listings_details.columns:
    if df_listings_details[col].apply(type).nunique() > 1:
        print(f"Mixed types still present in column: {col}")
    else:
        print(f"No mixed types in column: {col}")

No mixed types in column: id
No mixed types in column: name
No mixed types in column: space
No mixed types in column: experiences_offered
No mixed types in column: neighborhood_overview
No mixed types in column: access
No mixed types in column: street
No mixed types in column: neighbourhood
No mixed types in column: neighbourhood_cleansed
No mixed types in column: city
No mixed types in column: state
No mixed types in column: zipcode
No mixed types in column: smart_location
No mixed types in column: country_code
No mixed types in column: country
No mixed types in column: latitude
No mixed types in column: longitude
No mixed types in column: is_location_exact
No mixed types in column: property_type
No mixed types in column: room_type
No mixed types in column: accommodates
No mixed types in column: bathrooms
No mixed types in column: bedrooms
No mixed types in column: beds
No mixed types in column: bed_type
No mixed types in column: amenities
No mixed types in column: square_feet
No mixed types in column: price
No mixed types in column: weekly_price
No mixed types in column: monthly_price
No mixed types in column: security_deposit
No mixed types in column: cleaning_fee
No mixed types in column: guests_included
No mixed types in column: extra_people
No mixed types in column: minimum_nights
No mixed types in column: maximum_nights
No mixed types in column: calendar_updated
No mixed types in column: has_availability
No mixed types in column: availability_30
No mixed types in column: availability_60
No mixed types in column: availability_90
No mixed types in column: availability_365
No mixed types in column: number_of_reviews
No mixed types in column: review_scores_rating
No mixed types in column: review_scores_accuracy
No mixed types in column: review_scores_cleanliness
No mixed types in column: review_scores_checkin
No mixed types in column: review_scores_communication
No mixed types in column: review_scores_location
No mixed types in column: review_scores_value
No mixed types in column: requires_license
No mixed types in column: license
No mixed types in column: cancellation_policy
No mixed types in column: calculated_host_listings_count

In [90]:
for col in df_neighbourhoods.columns:
    types_in_column = df_neighbourhoods[col].apply(type).value_counts()
    if len(types_in_column) > 1:
        print(f"Mixed types in column: {col}")
    else:
        print(f"No mixed types in column: {col}")

No mixed types in column: neighbourhood

In [91]:
# Checking for duplicates in df_listings
df_listings_dups = df_listings[df_listings.duplicated()]
if not df_listings_dups.empty:
    print("Duplicates found in df_listings:")
    print(df_listings_dups)
else:
    print("No duplicates found in df_listings.")

# Checking for duplicates in df_calendar
df_calendar_dups = df_calendar[df_calendar.duplicated()]
if not df_calendar_dups.empty:
    print("Duplicates found in df_calendar:")
    print(df_calendar_dups)
else:
    print("No duplicates found in df_calendar.")

# Checking for duplicates in df_listings_details
df_listings_details_dups = df_listings_details[df_listings_details.duplicated()]
if not df_listings_details_dups.empty:
    print("Duplicates found in df_listings_details:")
    print(df_listings_details_dups)
else:
    print("No duplicates found in df_listings_details.")

# Checking for duplicates in df_neighbourhoods
df_neighbourhoods_dups = df_neighbourhoods[df_neighbourhoods.duplicated()]
if not df_neighbourhoods_dups.empty:
    print("Duplicates found in df_neighbourhoods:")
    print(df_neighbourhoods_dups)
else:
    print("No duplicates found in df_neighbourhoods.")

No duplicates found in df_listings.
No duplicates found in df_calendar.
No duplicates found in df_listings_details.
No duplicates found in df_neighbourhoods.

In [92]:
print("Descriptive Statistics for df_listings:")
print(df_listings.describe())
print("\n")

Descriptive Statistics for df_listings:
         listing_id       host_id      latitude     longitude  \
count  2.003000e+04  2.003000e+04  20030.000000  20030.000000
mean   1.541725e+07  4.868570e+07     52.365212      4.888977
std    8.569404e+06  5.649635e+07      0.015996      0.035573
min    2.818000e+03  3.159000e+03     52.288378      4.753247
25%    8.188423e+06  8.093516e+06     52.355126      4.863595
50%    1.563049e+07  2.369450e+07     52.364590      4.886387
75%    2.202577e+07  6.827535e+07     52.375074      4.908288
max    3.058041e+07  2.293612e+08     52.424713      5.027689

       price_per_night  minimum_nights  number_of_reviews  reviews_per_month  \
count     20030.000000    20030.000000       20030.000000       20030.000000
mean        152.181178        3.328707          21.560459           0.934503
std         145.828976       12.537419          43.240292           1.297465
min           0.000000        1.000000           0.000000           0.000000
25%          96.000000        2.000000           3.000000           0.170000
50%         125.000000        2.000000           8.000000           0.510000
75%         175.000000        3.000000          22.000000           1.090000
max        8500.000000     1001.000000         695.000000          11.850000

       calculated_host_listings_count  availability_365
count                    20030.000000      20030.000000
mean                         4.734698         59.913679
std                         22.921886        104.027710
min                          1.000000          0.000000
25%                          1.000000          0.000000
50%                          1.000000          3.000000
75%                          1.000000         67.000000
max                        208.000000        365.000000

In [93]:
print("Descriptive Statistics for df_calendar:")
print(df_calendar.describe())
print("\n")

Descriptive Statistics for df_calendar:
         listing_id
count  7.310950e+06
mean   1.541725e+07
std    8.569190e+06
min    2.818000e+03
25%    8.187901e+06
50%    1.563049e+07
75%    2.202612e+07
max    3.058041e+07

In [94]:
print("Descriptive Statistics for df_listings_details:")
print(df_listings_details.describe())
print("\n")

Descriptive Statistics for df_listings_details:
                 id      latitude     longitude  accommodates     bathrooms  \
count  2.003000e+04  20030.000000  20030.000000  20030.000000  20030.000000
mean   1.541725e+07     52.365212      4.888977      2.891912      1.137594
std    8.569404e+06      0.015996      0.035573      1.318760      0.793710
min    2.818000e+03     52.288378      4.753247      1.000000      0.000000
25%    8.188423e+06     52.355126      4.863595      2.000000      1.000000
50%    1.563049e+07     52.364590      4.886387      2.000000      1.000000
75%    2.202577e+07     52.375074      4.908288      4.000000      1.000000
max    3.058041e+07     52.424713      5.027689     17.000000    100.500000

           bedrooms          beds  square_feet         price  weekly_price  \
count  20030.000000  20030.000000   406.000000  20030.000000  20030.000000
mean       1.444883      1.848927   520.485222    152.181178    717.182177
std        0.885548      1.389512   544.557660    145.828976    177.929811
min        0.000000      0.000000     0.000000      0.000000    100.000000
25%        1.000000      1.000000     0.000000     96.000000    700.000000
50%        1.000000      1.000000   484.000000    125.000000    700.000000
75%        2.000000      2.000000   807.000000    175.000000    700.000000
max       12.000000     32.000000  4306.000000   8500.000000   6000.000000

       monthly_price  security_deposit  cleaning_fee  guests_included  \
count   20030.000000      20030.000000  20030.000000     20030.000000
mean     2230.782726        199.749526     38.497654         1.468997
std       439.235410        284.977526     22.021603         0.937890
min       550.000000          0.000000      0.000000         1.000000
25%      2200.000000        100.000000     30.000000         1.000000
50%      2200.000000        150.000000     35.000000         1.000000
75%      2200.000000        250.000000     49.000000         2.000000
max     20000.000000       4736.000000    531.000000        16.000000

       minimum_nights  maximum_nights  availability_30  availability_60  \
count    20030.000000    20030.000000     20030.000000     20030.000000
mean         3.328707      631.225711         4.905642        11.411233
std         12.537419      541.339981         7.942903        17.498603
min          1.000000        1.000000         0.000000         0.000000
25%          2.000000       21.000000         0.000000         0.000000
50%          2.000000     1125.000000         0.000000         0.000000
75%          3.000000     1125.000000         7.000000        18.000000
max       1001.000000     9999.000000        30.000000        60.000000

       availability_90  availability_365  number_of_reviews  \
count     20030.000000      20030.000000       20030.000000
mean         18.168597         59.913679          21.560459
std          27.704834        104.027710          43.240292
min           0.000000          0.000000           0.000000
25%           0.000000          0.000000           3.000000
50%           0.000000          3.000000           8.000000
75%          28.000000         67.000000          22.000000
max          90.000000        365.000000         695.000000

       review_scores_rating  review_scores_accuracy  \
count          20030.000000            20030.000000
mean              95.132851                9.722117
std                6.237760                0.647501
min               20.000000                2.000000
25%               93.000000               10.000000
50%               97.000000               10.000000
75%               99.000000               10.000000
max              100.000000               10.000000

       review_scores_cleanliness  review_scores_checkin  \
count               20030.000000           20030.000000
mean                    9.536246               9.770694
std                     0.828591               0.608730
min                     2.000000               2.000000
25%                     9.000000              10.000000
50%                    10.000000              10.000000
75%                    10.000000              10.000000
max                    10.000000              10.000000

       review_scores_communication  review_scores_location  \
count                 20030.000000            20030.000000
mean                      9.813779                9.498352
std                       0.563037                0.705727
min                       2.000000                2.000000
25%                      10.000000                9.000000
50%                      10.000000               10.000000
75%                      10.000000               10.000000
max                      10.000000               10.000000

       review_scores_value  calculated_host_listings_count
count         20030.000000                    20030.000000
mean              9.151772                        4.734698
std               0.752403                       22.921886
min               2.000000                        1.000000
25%               9.000000                        1.000000
50%               9.000000                        1.000000
75%              10.000000                        1.000000
max              10.000000                      208.000000

In [95]:
print("Descriptive Statistics for df_neighbourhoods:")
print(df_neighbourhoods.describe())
print("\n")

Descriptive Statistics for df_neighbourhoods:
          neighbourhood
count                22
unique               22
top     Bijlmer-Centrum
freq                  1

In [149]:
df_listings

,listing_id,name,host_id,neighbourhood,latitude,longitude,room_type,price_per_night,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2818,Quiet Garden View Room & Super Fast WiFi,3159,Oostelijk Havengebied - Indische Buurt,52.365755,4.941419,Private room,59.0,3,248,2018-11-28,2.10,1,44
1,3209,"Quiet apt near center, great view",3806,Westerpark,52.390225,4.873924,Entire home/apt,160.0,4,42,2018-08-29,1.03,1,47
2,20168,100%Centre-Studio 1 Private Floor/Bathroom,59484,Centrum-Oost,52.365087,4.893541,Entire home/apt,80.0,1,233,2018-11-30,2.18,2,198
3,25428,Lovely apt in City Centre (Jordaan),56142,Centrum-West,52.373114,4.883668,Entire home/apt,125.0,14,1,2018-01-21,0.09,2,141
4,27886,"Romantic, stylish B&B houseboat in canal district",97647,Centrum-West,52.386727,4.892078,Private room,150.0,2,171,2018-11-25,2.03,1,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20025,30576148,Family House City + free Parking+garden (160 m2),13399651,Watergraafsmeer,52.345999,4.952145,Entire home/apt,340.0,7,0,Never Reviewed,0.00,1,11
20026,30577727,Home Sweet Home in Indische Buurt,1595885,Oostelijk Havengebied - Indische Buurt,52.362412,4.932467,Entire home/apt,150.0,3,0,Never Reviewed,0.00,2,16
20027,30578037,Amsterdam Cozy apartment nearby center,87866499,Oud-Oost,52.362431,4.926912,Entire home/apt,80.0,10,0,Never Reviewed,0.00,2,210
20028,30579673,Home Sweet Home for a Guest or a Couple,1595885,Oostelijk Havengebied - Indische Buurt,52.363780,4.932493,Private room,55.0,2,0,Never Reviewed,0.00,2,31
20029,30580413,Cosy two bedroom appartment near 'de Pijp'!,27212057,De Pijp - Rivierenbuurt,52.346911,4.901932,Entire home/apt,220.0,5,0,Never Reviewed,0.00,1,14

In [151]:
df_calendar.head()

   listing_id        date available
0        2818  2019-12-05         f
1       73208  2019-08-30         f
2       73208  2019-08-29         f
3       73208  2019-08-28         f
4       73208  2019-08-27         f

In [155]:
df_listings_details.shape

(20030, 54)

In [157]:
df_neighbourhoods.head()

            neighbourhood
0         Bijlmer-Centrum
1            Bijlmer-Oost
2           Bos en Lommer
3  Buitenveldert - Zuidas
4            Centrum-Oost

In [159]:
df_calendar.to_csv(os.path.join(path, 'Calendar_Cleaned.csv'))

In [161]:
df_listings.to_csv(os.path.join(path, 'Listings_Cleaned.csv'))

In [163]:
df_listings_details.to_csv(os.path.join(path, 'Listings_Details_Cleaned.csv'))

In [165]:
df_neighbourhoods.to_csv(os.path.join(path, 'Neighbourhoods_Cleaned.csv'))